name: Build Minified Node.js
on: [workflow_dispatch] # 手动点击运行

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Node.js Source
        uses: actions/checkout@v4
        with:
          repository: nodejs/node
          ref: v20.18.3 # 指定版本
          fetch-depth: 1

      - name: Install NASM
        run: choco install nasm

      - name: Build Node.js (Minified)
        shell: cmd
        run: |
          :: 使用完整参数名称，确保 vcbuild 能正确识别并传给 python
          .\vcbuild.bat release x64 without-intl without-inspector


      - name: Upload Minified node.exe
        uses: actions/upload-artifact@v4
        with:
          name: minified-node-exe
          path: out/Release/node.exe
